# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\nicol\Desktop\Buscaminas\ventana1.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from ventana2 import Ui_MainWindow

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1256, 617)
        MainWindow.setMinimumSize(QtCore.QSize(1200, 100))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1261, 621))
        self.label.setLineWidth(3)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(560, 210, 361, 61))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(-1)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"\n"
"    background:transparent;\n"
"    color:white;\n"
"    border-radius: 6px;\n"
"    font-size:32px;\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(300, 380, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(-1)
      
        self.pushButton.setFont(font)
        self.pushButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton.setStyleSheet("QPushButton{\n"
"\n"
"    background:transparent;\n"
"    color:white;\n"
"    border-radius: 6px;\n"
"    font-size:18px;\n"
"    border-bottom: 2px solid white;\n"
"    border-top: 1px solid white;\n"
"    border-left: 1px solid white;\n"
"    border-right: 1px solid white;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    background:black;\n"
"    color:white;\n"
"    border-radius: 6px;\n"
"    font-size:14px;\n"
"    border-bottom: 2px solid black;\n"
"    border-top: 1px solid black;\n"
"    border-left: 1px solid black;\n"
"    border-right: 1px solid black;\n"
"}\n"
"")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(550, 380, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(-1)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"\n"
"    background:transparent;\n"
"    color:white;\n"
"    border-radius: 6px;\n"
"    font-size:18px;\n"
"    border-bottom: 2px solid white;\n"
"    border-top: 1px solid white;\n"
"    border-left: 1px solid white;\n"
"    border-right: 1px solid white;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    background:black;\n"
"    color:white;\n"
"    border-radius: 6px;\n"
"    font-size:14px;\n"
"    border-bottom: 2px solid black;\n"
"    border-top: 1px solid black;\n"
"    border-left: 1px solid black;\n"
"    border-right: 1px solid black;\n"
"}\n"
"")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(810, 380, 211, 51))
        font = QtGui.QFont()
        font.setFamily("Gadugi")
        font.setPointSize(-1)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"\n"
"    background:transparent;\n"
"    color:white;\n"
"    border-radius: 6px;\n"
"    font-size:18px;\n"
"    border-bottom: 2px solid white;\n"
"    border-top: 1px solid white;\n"
"    border-left: 1px solid white;\n"
"    border-right: 1px solid white;\n"
"}\n"
"QPushButton:hover{\n"
"\n"
"    background:black;\n"
"    color:white;\n"
"    border-radius: 6px;\n"
"    font-size:14px;\n"
"    border-bottom: 2px solid black;\n"
"    border-top: 1px solid black;\n"
"    border-left: 1px solid black;\n"
"    border-right: 1px solid black;\n"
"}\n"
"")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/iconosbuscaminas/ima3.jpg\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "BUSCACOVID"))
        self.pushButton.setText(_translate("MainWindow", "FACIL"))
        self.pushButton_2.setText(_translate("MainWindow", "NORMAL"))
        self.pushButton_3.setText(_translate("MainWindow", "DIFICIL"))



        self.pushButton.clicked.connect(self.abrir)
      

    def abrir(self):        # funcion que crea una nueva ventana y manda a llamar a la ventana 2

            self.ventana2 = QtWidgets.QMainWindow()
            self.ui = Ui_MainWindow()
            self.ui.setupUi(self.ventana2)          # Se cierra la primera ventana y se abre la segunda
            self.ventana2.show()
            print("goaasdd")
            MainWindow.destroy()

    




import Recursos.iconos


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
